### ISSUE TITLE
读取字体报错

### ISSUE THREAD

**Issue by Natane0808** [Travellerrr/AronaBot#2]
2024-04-20 09:13:30 E/AronaBot: java.lang.RuntimeException: java.io.IOException: Problem reading font data.
java.lang.RuntimeException: java.io.IOException: Problem reading font data.
        at AronaBot-1.0.1.mirai2.jar//cn.travellerr.tools.GFont.init(GFont.java:15)
        at AronaBot-1.0.1.mirai2.jar//cn.travellerr.AronaBot.onEnable(AronaBot.java:36)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:244)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:393)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:40)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:193)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:360)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Font.java:1205)
        at java.desktop/java.awt.Font.createFont(Font.java:1076)
        at AronaBot-1.0.1.mirai2.jar//cn.travellerr.tools.GFont.init(GFont.java:13)
        ... 24 more

**Comment by Echomirix** [comment]
能否详细给一下运行mcl的设备系统信息和复现手段？我在Linux Debian系统与Windows11系统上都没有发现这个报错……

**Comment by Natane0808** [comment]
# 系统是Rocky Linux 
![image](https://github.com/Travellerrr/AronaBot/assets/48778330/b8b1ed8e-b528-41ad-a6e7-ef793e196510)

# 在mcl一开始启动时就会报错
![image](https://github.com/Travellerrr/AronaBot/assets/48778330/38651730-ba10-4151-a373-a0a4afcd1f43)

![image](https://github.com/Travellerrr/AronaBot/assets/48778330/44838d2b-d5c2-4c8e-80ac-496f283901a2)

**Comment by Echomirix** [comment]
> # 系统是Rocky Linux
> ![image](https://private-user-images.githubusercontent.com/48778330/324172253-b8b1ed8e-b528-41ad-a6e7-ef793e196510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTc2MjksIm5iZiI6MTcxMzYxNzMyOSwicGF0aCI6Ii80ODc3ODMzMC8zMjQxNzIyNTMtYjhiMWVkOGUtYjUyOC00MWFkLWE2ZTctZWY3OTNlMTk2NTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyNDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlN2I4YzUxMTZkMGE5MTkxZDdiYzUyOWUxNzllMzk3ZGU1ZjQ3NTdkNjljZTEyNmUxZmU3YjRjMzI1NTk4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pUzhyONEqybofeJ_svWz56G0-YYHFUDX3VYuUjo6eL0)
> 
> # 在mcl一开始启动时就会报错
> ![image](https://private-user-images.githubusercontent.com/48778330/324172452-38651730-ba10-4151-a373-a0a4afcd1f43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTc2MjksIm5iZiI6MTcxMzYxNzMyOSwicGF0aCI6Ii80ODc3ODMzMC8zMjQxNzI0NTItMzg2NTE3MzAtYmExMC00MTUxLWEzNzMtYTBhNGFmY2QxZjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyNDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzRhZDUyNjk0Y2UyYjNhYjBmZDM5ZDc1OGRjZGZiOThmMWU1MmM0NTdlNTYxNDQxMzhlZjA2NjA5NWQ0YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dr_wD-LxjC2kBO_MWFT6KaZLLp7rsBLwE6YLCnb8Biw)
> 
> ![image](https://private-user-images.githubusercontent.com/48778330/324172342-44838d2b-d5c2-4c8e-80ac-496f283901a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTc2MjksIm5iZiI6MTcxMzYxNzMyOSwicGF0aCI6Ii80ODc3ODMzMC8zMjQxNzIzNDItNDQ4MzhkMmItZDVjMi00YzhlLTgwYWMtNDk2ZjI4MzkwMWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyNDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZWQyM2ZhMTI1MmQzZTY4MzlkMTIzYjVjMTE3ZTM3YmQzMzBiMzE4YzQyMzI5ZThkOTFkMjU1YjIxMzZhOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-vA5oRXhdy4pB95b_5TAyp_sV1-OwB55aUP7_WhsCb0)

尝试使用一下最新版的插件，配置自定义字体路径或许能够解决，只不过可能图片中的文字会有一点偏移

**Comment by Travellerrr** [comment]
> # 系统是Rocky Linux
> ![image](https://private-user-images.githubusercontent.com/48778330/324172253-b8b1ed8e-b528-41ad-a6e7-ef793e196510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTc2MjksIm5iZiI6MTcxMzYxNzMyOSwicGF0aCI6Ii80ODc3ODMzMC8zMjQxNzIyNTMtYjhiMWVkOGUtYjUyOC00MWFkLWE2ZTctZWY3OTNlMTk2NTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyNDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlN2I4YzUxMTZkMGE5MTkxZDdiYzUyOWUxNzllMzk3ZGU1ZjQ3NTdkNjljZTEyNmUxZmU3YjRjMzI1NTk4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pUzhyONEqybofeJ_svWz56G0-YYHFUDX3VYuUjo6eL0)
> 
> # 在mcl一开始启动时就会报错
> ![image](https://private-user-images.githubusercontent.com/48778330/324172452-38651730-ba10-4151-a373-a0a4afcd1f43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTc2MjksIm5iZiI6MTcxMzYxNzMyOSwicGF0aCI6Ii80ODc3ODMzMC8zMjQxNzI0NTItMzg2NTE3MzAtYmExMC00MTUxLWEzNzMtYTBhNGFmY2QxZjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyNDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzRhZDUyNjk0Y2UyYjNhYjBmZDM5ZDc1OGRjZGZiOThmMWU1MmM0NTdlNTYxNDQxMzhlZjA2NjA5NWQ0YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dr_wD-LxjC2kBO_MWFT6KaZLLp7rsBLwE6YLCnb8Biw)
> 
> ![image](https://private-user-images.githubusercontent.com/48778330/324172342-44838d2b-d5c2-4c8e-80ac-496f283901a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTc2MjksIm5iZiI6MTcxMzYxNzMyOSwicGF0aCI6Ii80ODc3ODMzMC8zMjQxNzIzNDItNDQ4MzhkMmItZDVjMi00YzhlLTgwYWMtNDk2ZjI4MzkwMWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyNDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZWQyM2ZhMTI1MmQzZTY4MzlkMTIzYjVjMTE3ZTM3YmQzMzBiMzE4YzQyMzI5ZThkOTFkMjU1YjIxMzZhOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-vA5oRXhdy4pB95b_5TAyp_sV1-OwB55aUP7_WhsCb0)

尝试使用一下最新版的插件，配置自定义字体路径或许能够解决，只不过可能图片中的文字会有一点偏移

**Comment by Natane0808** [comment]
找到原因了，系统太干净，fontconfig没有装。`yum install -y fontconfig`一下就好了
