### ISSUE TITLE
今日运势的jrys.db 始终为0B

### ISSUE THREAD

**Issue by yigekuyou** [Travellerrr/AronaBot#6]
command owned by AronaBot v1.1.2-alpha with Friend()
java.lang.RuntimeException: 出错了~
	at AronaBot-1.1.2-alpha.mirai2.jar//cn.travellerr.BlueArchive.GetSentenceApi.isQQNumberNew(GetSentenceApi.java:174)
	at AronaBot-1.1.2-alpha.mirai2.jar//cn.travellerr.BlueArchive.jrrp.info(jrrp.java:11)
	at AronaBot-1.1.2-alpha.mirai2.jar//cn.travellerr.command.GetJrrp.getJrrp(commandUtil.kt:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1$invokeSuspend$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: fortune)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.core.DB.newSQLException(DB.java:1179)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.core.DB.newSQLException(DB.java:1190)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.core.DB.throwex(DB.java:1150)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.core.DB.prepare(DB.java:264)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225)
	at AronaBot-1.1.2-alpha.mirai2.jar[private]//org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at AronaBot-1.1.2-alpha.mirai2.jar//cn.travellerr.BlueArchive.GetSentenceApi.isQQNumberNew(GetSentenceApi.java:167)
	... 21 more

**Comment by Echomirix** [comment]
这是因为创建空数据库后使用"今日人品”功能并没有生成 `fortune` 表
https://github.com/Travellerrr/AronaBot/commit/a7278699a18fed0a12d84a74ebbb486ea3be613f 提交中已修复，尝试使用 [v1.1.2正式版](https://github.com/Travellerrr/AronaBot/releases/tag/v1.1.2)
